; Drone & Drama — Teensy 4.0, Audio + OLED
[env:teensy40]
platform = teensy
board = teensy40
framework = arduino
upload_speed = 115200

lib_ldf_mode = deep+
lib_deps =
    https://github.com/dxinteractive/ResponsiveAnalogRead.git@^1.2.1
    adafruit/Adafruit SH110x
    adafruit/Adafruit GFX Library
    adafruit/Adafruit BusIO

monitor_speed = 115200
build_flags =
    -DSH110X_NO_SPLASH
    ; -DDEBUG